### ISSUE TITLE
"s3tk encrypt" clears object ACL during encryption

### ISSUE THREAD

**Issue by cxmcc** [ankane/s3tk#1]
"s3tk encrypt" clears object ACL during encryption.
I was expecting it preserves the object level ACL.

**Comment by ankane** [comment]
Hey @cxmcc, this is mentioned in the readme: "objects will lose any custom ACL". Since only private objects should need encryption, I think this should be fine.

**Comment by caseygoodrich** [comment]
Some companies require encryption at rest and the object even if its a public or private.  Its not always binary choice when it comes to S3 objects.  You could have special ACLs on the objects, Metadata, and storage type options.  Just resetting the object to its defaults is not always ideal.  I understand its a task to do this because even the AWS Cli does not do this.  Although in the GUI Console at AWS you can do this but not at the CLI.  That when i found your tool which is fast but the stripping of the ACL, metadata, and Storage class is not ideal.

**Comment by ankane** [comment]
@caseygoodrich Agree it's not ideal. Happy to accept a PR to change it.
